# golangci-lint configuration
version: 2

run:
  timeout: 5m
  tests: true

linters:
  # Use only the default linters
  disable:
    - unused  # Too noisy for now

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  fix: true