run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 20
  gosec:
    excludes:
      - G304
      - G204
      - G306

exclude:
  - path: third_party$
  - path: builtin$
  - path: examples$

exclude-rules:
  - linters:
      - errcheck
      - gosec
      - prealloc
    path: _test\.go
  - linters:
      - gosec
    path: internal/executor/executor.go
    text: 'G204:'
  - linters:
      - gosec
    path: internal/config/config.go
    text: 'G304:'
  - linters:
      - gosec
    path: cmd/init.go
    text: 'G306:'
  - linters:
      - gocyclo
    path: cmd/
  - linters:
      - gocyclo
    path: _test\.go$

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
