version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G304
        - G204
        - G306
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - prealloc
        path: _test\.go
      - linters:
          - gosec
        path: internal/executor/executor.go
        text: 'G204:'
      - linters:
          - gosec
        path: internal/config/config.go
        text: 'G304:'
      - linters:
          - gosec
        path: cmd/init.go
        text: 'G306:'
      - linters:
          - gocyclo
        path: cmd/
      - linters:
          - gocyclo
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

