version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: simple-mcp-runner
    main: ./main.go
    binary: simple-mcp-runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/mjmorales/simple-mcp-runner/cmd.version={{.Version}}
      - -X github.com/mjmorales/simple-mcp-runner/cmd.commit={{.Commit}}
      - -X github.com/mjmorales/simple-mcp-runner/cmd.date={{.Date}}

archives:
  - id: simple-mcp-runner
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: mjmorales
    name: simple-mcp-runner
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/mjmorales/simple-mcp-runner/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - repository:
      owner: mjmorales
      name: homebrew-tap
    name: simple-mcp-runner
    description: "A Model Context Protocol (MCP) server for safe local command execution"
    homepage: "https://github.com/mjmorales/simple-mcp-runner"
    license: "MIT"
    test: |
      system "#{bin}/simple-mcp-runner", "version"